#!/usr/bin/env escript
%% vim: ts=4 sw=4 et ft=erlang
%%! -pa lib/yamerl/ebin -pa ebin -Wall

-include("escript_stdin.erl").

progname() -> "convert yep to erlang".

chunk(Data, Filename) -> 
    ok = application:start(yamerl),
    Yaml = yamerl_constr:string(Data),
    Erlang = yep_erlang:module(Yaml, Filename),
    io:format("~s", [Erlang]).

